- hosts: localhost
  vars_files:
          - aws_credentials.yml
  tasks:
          - name: "start an instance and Add EBS"
            ec2_instance:
                    name: "ansible-os"
                    region: "ap-south-1"
                    vpc_subnet_id: subnet-6cdfb420
                    image_id: ami-0a9d27a9f4f5c0efc
                    instance_type: "t2.micro"
                    key_name: "mykey"
                    security_group: sg-044a0097d95b73760
                    aws_access_key: "{{ access_key }}"
                    aws_secret_key: "{{ secret_key }}"
          - name: "Refreshing Inventory"
            meta: refresh_inventory

- hosts: all
  become: yes
  remote_user: ec2-user
  tasks:
          - package:
                  name: httpd
                  state: present
          - copy:
                  dest: "/var/www/html/index.html"
                  content: "AWS Server launched from Ansible"
          - service:
                  name: "httpd"
                  state: restarted 

