- hosts: target
  tasks:
          - name: "configuring yum repository"
            yum_repository:
                    name: docker
                    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                    description: repo for docker
                    gpgcheck: no

          - name: "installing docker"
            command:
                    cmd: "yum install docker-ce --nobest -y"
                    warn: no
          - name: "Starting docker"
            service:
                    name: docker
                    state: started
          - name: "installing docker-py"
            pip:
                    name: docker-py
          - name: "copying webpage"
            copy:
                    src: index.html
                    dest: /var/www/html/
          - name: "starting container"
            docker_container:
                    name: ansible-httpd
                    image: httpd
                    state: started
                    ports: 8081:80
                    volumes:
                            - /var/www/html:/usr/local/apache2/htdocs/
          - name: "configuring firewall"
            firewalld:
                    port: "8081/tcp"
                    state: enabled
                    permanent: true
